---
title: "Violence Score"
author: "Caroline Wang"
output: html_notebook
date: "April 18, 2019"
purpose: checking data assumptions and exploratory analysis with the violence score
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=F, message=F,echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(segmented)
source('functions.r')

load("Table_construction.Rdata") 
```

```{r}
features = features %>%
  # Add other useful information:
  inner_join(
    data_before %>% 
      select(person_id, screening_date, people) %>%
      unnest() %>%
      select(person_id, screening_date, race, sex, name),
    by = c("person_id","screening_date")
  ) %>%
  inner_join(features_on, by = c("person_id","screening_date")) %>%
  inner_join(outcomes, by = c("person_id","screening_date")) %>%
  #duplicate columns
  select(-c(offenses_within_30.x,offenses_within_30.y)) %>%
  
  # Create as many features as possible:
  mutate(
    raw_score = `Risk of Violence_raw_score`, # Adjust for violent/general
    decile_score = `Risk of Violence_decile_score`, # Adjust for violent/general
    p_juv_fel_count = pmin(p_juv_fel_count,2),
    p_felprop_violarrest = pmin(p_felprop_violarrest,5),
    p_murder_arrest = pmin(p_murder_arrest,3),
    p_felassault_arrest = pmin(p_felassault_arrest,3),
    p_misdemassault_arrest = pmin(p_misdemassault_arrest,3),
    #p_famviol_arrest = pmin(p_famviol_arrest,3),
    p_sex_arrest = pmin(p_sex_arrest,3),
    p_weapons_arrest = pmin(p_weapons_arrest,3),
    p_n_on_probation = pmin(p_n_on_probation,5),
    p_current_on_probation = pmin(p_current_on_probation,5),
    p_prob_revoke = pmin(p_prob_revoke,5),
    race_black = if_else(race=="African-American",1,0),
    race_white = if_else(race=="Caucasian",1,0),
    race_hispanic = if_else(race=="Hispanic",1,0),
    race_asian = if_else(race=="Asian",1,0),
    race_native = if_else(race=="Native American",1,0), # race == "Other" is the baseline
    
    # Subscales:
    vio_hist = p_juv_fel_count+
      p_felprop_violarrest+
      p_murder_arrest+
      p_felassault_arrest+
      p_misdemassault_arrest+
      #p_famviol_arrest+ #because no observations have nonzero for this
      p_sex_arrest+
      p_weapons_arrest,
    history_noncomp = p_prob_revoke+
      p_probation+p_current_on_probation+
      p_n_on_probation,
    
    # Filters (TRUE for obserations to keep)
    filt1 = `Risk of Recidivism_decile_score` != -1, `Risk of Violence_decile_score` != -1, # Filter 1
    filt3 = !is.na(current_offense_date), # Filter 3
    filt4 = current_offense_date <= current_offense_date_limit, # Filter 4
    filt5 = p_current_age >= 18 & p_current_age <= 65,  # Filter 5
    filt_age = p_current_age == p_age_first_offense,
    filt6 = vio_hist == 0 , # Filter 6
    filt7 = history_noncomp==0 # Filter 7
  )
```

## Fit age polynomial
```{r}
features_age_poly = features %>%
  filter(filt1,filt5, filt6, filt7) 

lb_age = features_age_poly %>%
  group_by(p_current_age) %>%
  arrange(raw_score) %>%
  top_n(n=-1, wt=raw_score) # Fit lower bound on smallest value


mdl_age = lm(raw_score ~ 
               I(p_current_age^4) + 
               I(p_current_age^3) + 
               I(p_current_age^2) + 
               p_current_age, 
             data=lb_age)

# More precision for paper
summary(mdl_age)
print("Coefficients:")
sprintf("%.20e",mdl_age$coefficients) # More precision for paper

## Add f(age) to features and add filter
features = features %>%
  mutate(
    age_poly = predict(mdl_age, newdata=data.frame(p_current_age=p_current_age)),
    raw_score__age_poly = raw_score - age_poly,
    filt8 = raw_score >= age_poly - 0.05
  )

## Add same columns as above to lb_age 
lb_age = lb_age %>% 
    mutate(
    age_poly = predict(mdl_age, newdata=data.frame(p_current_age=p_current_age)),
    raw_score__age_poly = raw_score - age_poly,
    filt8 = raw_score >= age_poly - 0.05
    )
```

Plotting settings for age analysis
```{r}
xmin = 18
xmax = 65
xx = seq(xmin,xmax, length.out = 1000)
```

## Age polynomial plot
Generate a preliminary plot of age vs COMPAS violence score
```{r}
ggplot()+
  geom_point(aes(x=p_current_age, raw_score, color = factor(filt8)),alpha=.3, data=lb_age) +
  geom_line(aes(x=xx, predict(mdl_age, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("Violence score") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")

ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_age_poly) +
  geom_line(aes(x=xx, predict(mdl_age, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("Violence score") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")

#count of how many people for each age satisfy Data Assumptions (as well as we can check)
dat_assumptions_count = 
  ggplot(aes(p_current_age), data= filter(features_age_poly, filt_age))+
  geom_bar(fill ="#619CFF") + 
  theme_bw()+
  xlim(xmin,xmax)+
  ylim(0, 250) + 
  xlab("Age at COMPAS screening date") +
  ylab("Count of Individuals \n Violence Score") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")
dat_assumptions_count

```

```{r}
ggsave("Figures/dat_assumptions_count_viol.pdf",plot = dat_assumptions_count, width = 6, height = 4, units = "in")

```


```{r}
#Filter out outliers under the age polynomial, individuals with 
#noncomp history/violence history != 0
features_age_poly2 = features %>% 
    filter(filt1, filt5, filt6, filt7, filt8) 
    # filter(p_age_first_offense == p_current_age)

lb_filt = features_age_poly2 %>%
  group_by(p_current_age) %>%
    arrange(raw_score)%>%
    top_n(n=-1, wt = raw_score)

```


Generating new age spline. 
```{r}
mdl_age_spline <- segmented(lm(raw_score ~ p_current_age, data = lb_filt), 
                            seg.Z = ~p_current_age, psi = list(p_current_age = c(22,36,44)),
  control = seg.control(display = FALSE)
)

#Add Filter 9
features = features %>%
  mutate(
    age_spline = predict(mdl_age_spline, newdata=data.frame(p_current_age=p_current_age)),
    raw_score__age_spline = raw_score - age_spline,
    filt9 = raw_score >= age_spline - 0.05
  )

```


Examining individuals in lb_filt where age at first offense != current age
```{r}

#plot of age at first offense != current age in red with inds in lb_filt
fireplot_lb_viol = ggplot()+
  geom_point(aes(x=p_current_age, y = raw_score,colour = p_current_age == p_age_first_offense ), 
             alpha=.3, data=lb_filt %>% na.omit()) +
  scale_colour_manual(name='Current age equal to age at first arrest', values = setNames(c('red','#619CFF'),c(F, T))) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("\n Age at COMPAS screening date") +
  ylab("Violence score \n") +
  theme(text = element_text(size=16),
        axis.text=element_text(size=16), 
        legend.position ="top")
fireplot_lb_viol

#same plot as above but with everybody in features
fireplot_all_viol = ggplot()+
  geom_point(aes(x=p_current_age, y = raw_score, colour = p_current_age == p_age_first_offense ), 
             alpha=.2, data=features_age_poly2 %>% 
                            na.omit() %>%
                            mutate(p_current_age = ifelse(p_current_age == p_age_first_offense, 
                                                          p_current_age, 
                                                          p_current_age+.5))
             ) +
  scale_colour_manual(name='Current age equal to age at first arrest', values = setNames(c('red','#619CFF'),c(F, T))) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("\n Age at COMPAS screening date") +
  ylab("Violence score \n") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18), 
        legend.position ="top")
fireplot_all_viol


#plot of score vs age at first arrest
age_first_offense_viol = ggplot()+
  geom_point(aes(x=p_age_first_offense, raw_score), color="#619CFF",alpha=.3, 
             data=features_age_poly2) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("\n Age at First Offense") +
  ylab("Violence score \n") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")
age_first_offense_viol

#plot of score vs current age and age at first arrest
reverse_fireplot_all_viol = ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.2, 
             data=features_age_poly2 %>% 
                  na.omit() %>%
                  mutate(p_current_age = p_current_age+0.5 )) +
  geom_point(aes(x=p_age_first_offense, raw_score), color="red",alpha=.04, 
             data=features_age_poly2) +
  scale_colour_manual(name='Legend', values = setNames(c('red','#619CFF'),c("Age at first offense", "Current age"))) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("\n Age") +
  ylab("Violence score \n") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")
reverse_fireplot_all_viol

#Plotting people in lb, so that points which repeat more are larger. 
lb_inds_freq_viol = ggplot()+
  stat_sum(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.7, data=lb_filt) +
  theme_bw() +
  xlim(xmin,xmax) +
  xlab("\n Age at COMPAS screening date") +
  ylab("Violence score\n ") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")
lb_inds_freq_viol
```


Save figures for paper
```{r}
ggsave("Figures/fireplot_all_viol.pdf",plot = fireplot_all_viol, width = 6, height = 4, units = "in")
ggsave("Figures/age_first_offense_viol.pdf",plot = age_first_offense_viol, width = 6, height = 4, units = "in")
ggsave("Figures/reverse_fireplot_all_viol.pdf",plot = reverse_fireplot_all_viol, width = 6, height = 4, units = "in")
ggsave("Figures/lb_inds_freq_viol.pdf",plot = lb_inds_freq_viol, width = 6, height = 4, units = "in")

```

### Age at first offense analysis
```{r}
#History of noncomp = 0, violence history = 0 
features_scales0 <- features %>% 
    filter(filt1, filt5, filt6, filt7,filt9)

age_first_offense_viol_scales0 <- ggplot()+
  geom_point(aes(x=p_age_first_offense, 
                 y= raw_score__age_spline), 
                 color = "#619CFF",
                 alpha=.3, 
                 data=features_scales0) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at First Arrest") +
  ylab("Violence score - age spline") +
  ggtitle("Violence History & Noncomp. History = 0") + 
  theme(text = element_text(size=18),
        axis.text=element_text(size=14),
        legend.position="none")

age_first_offense_viol_scales0


#History of noncomp = 1, violence history = 1, age at first offense != current age 
features_scales1 <- features %>% 
    filter(filt1, filt5,filt9, 
           vio_hist == 1, 
           history_noncomp == 1, 
           p_age_first_offense != p_current_age)

age_first_offense_viol_scales1 <- ggplot()+
  geom_point(aes(x=p_age_first_offense, 
                 y= raw_score__age_spline), 
                 color = "#619CFF",
                 alpha=.3, 
                 data=features_scales1) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at First Arrest") +
  ylab("Violence score - age spline") +
  ggtitle("Violence History & Noncomp. History = 1, \nCurrent Age != Age at First Arrest") + 
  theme(text = element_text(size=18),
        axis.text=element_text(size=14),
        legend.position="none")

age_first_offense_viol_scales1


```




```{r}
ggsave("Figures/age_first_offense_viol_scales0.pdf", plot = age_first_offense_viol_scales0, width = 6.5, height = 4, units = "in")

ggsave("Figures/age_first_offense_viol_scales1.pdf", plot = age_first_offense_viol_scales1, width = 6.5, height = 4, units = "in")

```


