---
title: "age-spline-recid"
author: "Caroline Wang"
date: "March 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=F, message=F,echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(segmented)
source('functions.r')

load("Table_construction2.Rdata") #loading beau's version of data
```


```{r}
features = features %>%
  # Add other useful information:
  inner_join(
    data_before %>% 
      select(person_id, screening_date, people) %>%
      unnest() %>%
      select(person_id, screening_date, race, sex, name),
    by = c("person_id","screening_date")
  ) %>%
  inner_join(features_on, by = c("person_id","screening_date")) %>%
  inner_join(outcomes, by = c("person_id","screening_date")) %>%
    select(-c(offenses_within_30.x,offenses_within_30.y)) %>%

  # Create as many features as possible:
  mutate(
    raw_score = `Risk of Recidivism_raw_score`, # Adjust for violent/general
    decile_score = `Risk of Recidivism_decile_score`, # Adjust for violent/general
    p_jail30 = pmin(p_jail30,5),
    p_prison30 = pmin(p_jail30,5),
    p_prison = pmin(p_prison,5),
    p_probation = pmin(p_probation,5),
    race_black = if_else(race=="African-American",1,0),
    race_white = if_else(race=="Caucasian",1,0),
    race_hispanic = if_else(race=="Hispanic",1,0),
    race_asian = if_else(race=="Asian",1,0),
    race_native = if_else(race=="Native American",1,0), # race == "Other" is the baseline
    
    # Subscales:
    crim_inv = p_charge+
      p_jail30+
      p_prison+
      p_probation,
    
    # Filters (TRUE for obserations to keep)
    filt1 = `Risk of Recidivism_decile_score` != -1, `Risk of Violence_decile_score` != -1, 
    filt2 = offenses_within_30.x == 1,
    filt3 = !is.na(current_offense_date), 
    filt4 = current_offense_date <= current_offense_date_limit, 
    filt5 = p_current_age > 18 & p_current_age <= 65, 
    filt6 = crim_inv == 0  
  )
```


Modelling the COMPAS Risk of Recidivism score with a quadratic poly.
```{r}
features_age_poly = features %>%
  filter(filt1,filt5, filt6) 


#filter out any individiuals with crim inv history on lb of age poly
lb_age = features_age_poly %>%
  group_by(p_current_age) %>%
  arrange(raw_score) %>%
  top_n(n=-1, wt=raw_score) # Fit lower bound on smallest value

mdl_age = lm(raw_score ~ 
               I(p_current_age^2) + 
               p_current_age, 
             data=lb_age)

# More precision for paper
summary(mdl_age)

print("Coefficients:")
sprintf("%.20e",mdl_age$coefficients) # More precision for paper

## Add f(age) to features
features = features %>%
  mutate(
    f_age = predict(mdl_age, newdata=data.frame(p_current_age=p_current_age)),
    raw_score__f_age = raw_score - f_age,
    filt7 = raw_score >= f_age - 0.05
  )
## Add same filters to lb_age 
lb_age = lb_age %>% 
    mutate(
    f_age = predict(mdl_age, newdata=data.frame(p_current_age=p_current_age)),
    raw_score__f_age = raw_score - f_age,
    filt7 = raw_score >= f_age - 0.05
    )

```

Plotting settings
```{r}
xmin = 18
xmax = 65
xx = seq(xmin,xmax, length.out = 1000)
```

## Age polynomial plot
Generate a preliminary plot of age vs COMPAS general score
```{r}

ggplot()+
  geom_point(aes(x=p_current_age, raw_score, color = factor(filt7)),alpha=.3, data=lb_age) +
  geom_line(aes(x=xx, predict(mdl_age, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("General score") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")


ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_age_poly) +
  geom_line(aes(x=xx, predict(mdl_age, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("General score") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position="none")



```



```{r}
features_age_poly2 = features %>% 
    filter(filt1, filt5, filt6, filt7) 
  

lb_filt = features_age_poly2 %>%
  group_by(p_current_age) %>%
    arrange(raw_score)%>%
    top_n(n=-1, wt = raw_score)

#filtered out points 
lb_outliers = rbind(
                #reason not included in lb_filt was  
                #age not above age poly
                setdiff(lb_age, lb_filt) %>%
                  filter(!filt7) %>% #below age poly
                  mutate(reason = "Below age polynomial")
                
                ) 

lb = lb_filt %>% 
     select(p_current_age, p_age_first_offense, raw_score) %>%
     mutate(reason = "Used to construct linear splines") %>%
     rbind(lb_outliers)

```



Generating linear splines to fit the lower 
Plottng individuals on new bottom edge produced by fitting to lb_filt individuals. 
```{r}
mdl_age_spline <- segmented(lm(raw_score ~ p_current_age, data = lb_filt), 
                            seg.Z = ~p_current_age, psi = list(p_current_age = c(39,58)),
  control = seg.control(display = FALSE)
)
#Add Filter 8
features = features %>%
  mutate(
    age_spline = predict(mdl_age_spline, newdata=data.frame(p_current_age=p_current_age)),
    raw_score__age_spline = raw_score - age_spline,
    filt8 = raw_score >= age_spline - 0.05
  )
```

```{r}
mdl_age_spline
intercept(mdl_age_spline)
slope(mdl_age_spline)

```




```{r}
summary.segmented(mdl_age_spline)$psi
break1 =  summary.segmented(mdl_age_spline)$psi[1,2]
break2 =  summary.segmented(mdl_age_spline)$psi[2,2]

xx1 = seq(xmin,break1, length.out=1000)
xx2 = seq(break1,break2, length.out=1000)
xx3 = seq(break2,xmax, length.out=1000)

age_spline_recid = 
  ggplot()+
  geom_point(aes(x=p_current_age, raw_score, color= factor(reason)),alpha=.5, data=lb ) +
  scale_color_manual(values=c("red", "grey25")) + 
  geom_line(aes(x=xx1, y = predict(mdl_age_spline, newdata=data.frame(p_current_age=xx1))),
                color="darkorange1", size = 1) +
  geom_line(aes(x=xx2, y = predict(mdl_age_spline, newdata=data.frame(p_current_age=xx2))),
                color="cyan3", size = 1) +
  geom_line(aes(x=xx3, y = predict(mdl_age_spline, newdata=data.frame(p_current_age=xx3))),
                color="seagreen3", size = 1) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("\n Age at COMPAS screening date") +
  ylab("General Score \n") +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position = c(.95,.95),
        legend.title = element_blank(),
        legend.justification = c("right", "top"),
        legend.key = element_rect(fill = "aliceblue"),
        legend.background = element_rect(fill="aliceblue",
                                  size=0.5, linetype="solid")
        )

age_spline_recid

age_spline_recid_all = 
  ggplot()+
  geom_point(aes(x=p_current_age, raw_score, color= factor(reason)),alpha=.5, data=lb ) +
  scale_color_manual(values=c("red", "grey25")) + 
  geom_line(aes(x=xx1, y = predict(mdl_age_spline, newdata=data.frame(p_current_age=xx1))),
                color="#F8766D", size = 1) +
  geom_line(aes(x=xx2, y = predict(mdl_age_spline, newdata=data.frame(p_current_age=xx2))),
                color="#F8766D", size = 1) +
  geom_line(aes(x=xx3, y = predict(mdl_age_spline, newdata=data.frame(p_current_age=xx3))),
                color="#F8766D", size = 1) +
  
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_age_poly2) +

  theme_bw()+
  xlim(xmin,xmax)+
  labs(
    x = "\n Age at COMPAS screening date", 
    y = "General Score \n"
  ) +
  theme(text = element_text(size=18),
        axis.text=element_text(size=18),
        legend.position = "none"
        )

age_spline_recid_all

```

```{r}
ggsave("Figures/age_spline_recid.pdf",plot = age_spline_recid, width = 6, height = 4, units = "in")
ggsave("Figures/age_spline_recid_all.pdf",plot = age_spline_recid_all, width = 6, height = 4, units = "in")

```
