---
title: "check_arrests"
author: "Caroline Wang"
date: "December 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(tidyverse)
library(magrittr)
source('functions.r')

load("Table_construction.Rdata") 
```

## Look up person IDs
```{r}
features = features %>%
  # Add other useful information:
  inner_join(
    data_before_on %>% 
      select(person_id, screening_date, people) %>%
      unnest() %>%
      select(person_id, screening_date, race, sex, name),
    by = c("person_id","screening_date")
  ) %>%
  inner_join(features_on, by = c("person_id","screening_date")) %>%
  inner_join(outcomes, by = c("person_id","screening_date")) %>%
    select(-c(offenses_within_30)) 

```


# Potential problem: more arrests than charges? Must check data processing.
Much better now. 
```{r}
res_df = features %>% 
        filter(person_id %in% c(11312)) %>%
        # select(person_id, screening_date, name, p_charge, p_arrest, current_offense_date, ) %>%
        mutate(arrest_check = p_charge>=p_arrest) 
  
View(res_df)


table(res_df$arrest_check)
```

